INSERT INTO currencies (country_name, currency_name, cna3, cnn3, minor_unit, currency_is_on, currency_state)
VALUES
('AFGHANISTAN','Afghani','AFN','971','2',FALSE,'IN_USE'),
('ÅLAND ISLANDS','Euro','EUR','978','2',FALSE,'IN_USE'),
('ALBANIA','Lek','ALL','008','2',FALSE,'IN_USE'),
('ALGERIA','Algerian Dinar','DZD','012','2',FALSE,'IN_USE'),
('AMERICAN SAMOA','US Dollar','USD','840','2',FALSE,'IN_USE'),
('ANDORRA','Euro','EUR','978','2',FALSE,'IN_USE'),
('ANGOLA','Kwanza','AOA','973','2',FALSE,'IN_USE'),
('ANGUILLA','East Caribbean Dollar','XCD','951','2',FALSE,'IN_USE'),
('ANTARCTICA','No universal currency',DEFAULT,DEFAULT,DEFAULT,FALSE,'IN_USE'),
('ANTIGUA AND BARBUDA','East Caribbean Dollar','XCD','951','2',FALSE,'IN_USE'),
('ARGENTINA','Argentine Peso','ARS','032','2',FALSE,'IN_USE'),
('ARMENIA','Armenian Dram','AMD','051','2',FALSE,'IN_USE'),
('ARUBA','Aruban Florin','AWG','533','2',FALSE,'IN_USE'),
('AUSTRALIA','Australian Dollar','AUD','036','2',FALSE,'IN_USE'),
('AUSTRIA','Euro','EUR','978','2',FALSE,'IN_USE'),
('AZERBAIJAN','Azerbaijan Manat','AZN','944','2',FALSE,'IN_USE'),
('BAHAMAS (THE)','Bahamian Dollar','BSD','044','2',FALSE,'IN_USE'),
('BAHRAIN','Bahraini Dinar','BHD','048','3',FALSE,'IN_USE'),
('BANGLADESH','Taka','BDT','050','2',FALSE,'IN_USE'),
('BARBADOS','Barbados Dollar','BBD','052','2',FALSE,'IN_USE'),
('BELARUS','Belarusian Ruble','BYN','933','2',FALSE,'IN_USE'),
('BELGIUM','Euro','EUR','978','2',FALSE,'IN_USE'),
('BELIZE','Belize Dollar','BZD','084','2',FALSE,'IN_USE'),
('BENIN','CFA Franc BCEAO','XOF','952','0',FALSE,'IN_USE'),
('BERMUDA','Bermudian Dollar','BMD','060','2',FALSE,'IN_USE'),
('BHUTAN','Indian Rupee','INR','356','2',FALSE,'IN_USE'),
('BHUTAN','Ngultrum','BTN','064','2',FALSE,'IN_USE'),
('BOLIVIA (PLURINATIONAL STATE OF)','Boliviano','BOB','068','2',FALSE,'IN_USE'),
('BOLIVIA (PLURINATIONAL STATE OF)','Mvdol','BOV','984','2',FALSE,'IN_USE'),
('BONAIRE, SINT EUSTATIUS AND SABA','US Dollar','USD','840','2',FALSE,'IN_USE'),
('BOSNIA AND HERZEGOVINA','Convertible Mark','BAM','977','2',FALSE,'IN_USE'),
('BOTSWANA','Pula','BWP','072','2',FALSE,'IN_USE'),
('BOUVET ISLAND','Norwegian Krone','NOK','578','2',FALSE,'IN_USE'),
('BRAZIL','Brazilian Real','BRL','986','2',FALSE,'IN_USE'),
('BRITISH INDIAN OCEAN TERRITORY (THE)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('BRUNEI DARUSSALAM','Brunei Dollar','BND','096','2',FALSE,'IN_USE'),
('BULGARIA','Bulgarian Lev','BGN','975','2',FALSE,'IN_USE'),
('BURKINA FASO','CFA Franc BCEAO','XOF','952','0',FALSE,'IN_USE'),
('BURUNDI','Burundi Franc','BIF','108','0',FALSE,'IN_USE'),
('CABO VERDE','Cabo Verde Escudo','CVE','132','2',FALSE,'IN_USE'),
('CAMBODIA','Riel','KHR','116','2',FALSE,'IN_USE'),
('CAMEROON','CFA Franc BEAC','XAF','950','0',FALSE,'IN_USE'),
('CANADA','Canadian Dollar','CAD','124','2',FALSE,'IN_USE'),
('CAYMAN ISLANDS (THE)','Cayman Islands Dollar','KYD','136','2',FALSE,'IN_USE'),
('CENTRAL AFRICAN REPUBLIC (THE)','CFA Franc BEAC','XAF','950','0',FALSE,'IN_USE'),
('CHAD','CFA Franc BEAC','XAF','950','0',FALSE,'IN_USE'),
('CHILE','Chilean Peso','CLP','152','0',FALSE,'IN_USE'),
('CHILE','Unidad de Fomento','CLF','990','4',FALSE,'IN_USE'),
('CHINA','Yuan Renminbi','CNY','156','2',FALSE,'IN_USE'),
('CHRISTMAS ISLAND','Australian Dollar','AUD','036','2',FALSE,'IN_USE'),
('COCOS (KEELING) ISLANDS (THE)','Australian Dollar','AUD','036','2',FALSE,'IN_USE'),
('COLOMBIA','Colombian Peso','COP','170','2',FALSE,'IN_USE'),
('COLOMBIA','Unidad de Valor Real','COU','970','2',FALSE,'IN_USE'),
('COMOROS (THE)','Comorian Franc ','KMF','174','0',FALSE,'IN_USE'),
('CONGO (THE DEMOCRATIC REPUBLIC OF THE)','Congolese Franc','CDF','976','2',FALSE,'IN_USE'),
('CONGO (THE)','CFA Franc BEAC','XAF','950','0',FALSE,'IN_USE'),
('COOK ISLANDS (THE)','New Zealand Dollar','NZD','554','2',FALSE,'IN_USE'),
('COSTA RICA','Costa Rican Colon','CRC','188','2',FALSE,'IN_USE'),
('CÔTE D IVOIRE','CFA Franc BCEAO','XOF','952','0',FALSE,'IN_USE'),
('CROATIA','Kuna','HRK','191','2',FALSE,'IN_USE'),
('CUBA','Cuban Peso','CUP','192','2',FALSE,'IN_USE'),
('CUBA','Peso Convertible','CUC','931','2',FALSE,'IN_USE'),
('CURAÇAO','Netherlands Antillean Guilder','ANG','532','2',FALSE,'IN_USE'),
('CYPRUS','Euro','EUR','978','2',FALSE,'IN_USE'),
('CZECHIA','Czech Koruna','CZK','203','2',FALSE,'IN_USE'),
('DENMARK','Danish Krone','DKK','208','2',FALSE,'IN_USE'),
('DJIBOUTI','Djibouti Franc','DJF','262','0',FALSE,'IN_USE'),
('DOMINICA','East Caribbean Dollar','XCD','951','2',FALSE,'IN_USE'),
('DOMINICAN REPUBLIC (THE)','Dominican Peso','DOP','214','2',FALSE,'IN_USE'),
('ECUADOR','US Dollar','USD','840','2',FALSE,'IN_USE'),
('EGYPT','Egyptian Pound','EGP','818','2',FALSE,'IN_USE'),
('EL SALVADOR','El Salvador Colon','SVC','222','2',FALSE,'IN_USE'),
('EL SALVADOR','US Dollar','USD','840','2',FALSE,'IN_USE'),
('EQUATORIAL GUINEA','CFA Franc BEAC','XAF','950','0',FALSE,'IN_USE'),
('ERITREA','Nakfa','ERN','232','2',FALSE,'IN_USE'),
('ESTONIA','Euro','EUR','978','2',FALSE,'IN_USE'),
('ESWATINI','Lilangeni','SZL','748','2',FALSE,'IN_USE'),
('ETHIOPIA','Ethiopian Birr','ETB','230','2',FALSE,'IN_USE'),
('EUROPEAN UNION','Euro','EUR','978','2',FALSE,'IN_USE'),
('FALKLAND ISLANDS (THE) [MALVINAS]','Falkland Islands Pound','FKP','238','2',FALSE,'IN_USE'),
('FAROE ISLANDS (THE)','Danish Krone','DKK','208','2',FALSE,'IN_USE'),
('FIJI','Fiji Dollar','FJD','242','2',FALSE,'IN_USE'),
('FINLAND','Euro','EUR','978','2',FALSE,'IN_USE'),
('FRANCE','Euro','EUR','978','2',FALSE,'IN_USE'),
('FRENCH GUIANA','Euro','EUR','978','2',FALSE,'IN_USE'),
('FRENCH POLYNESIA','CFP Franc','XPF','953','0',FALSE,'IN_USE'),
('FRENCH SOUTHERN TERRITORIES (THE)','Euro','EUR','978','2',FALSE,'IN_USE'),
('GABON','CFA Franc BEAC','XAF','950','0',FALSE,'IN_USE'),
('GAMBIA (THE)','Dalasi','GMD','270','2',FALSE,'IN_USE'),
('GEORGIA','Lari','GEL','981','2',FALSE,'IN_USE'),
('GERMANY','Euro','EUR','978','2',FALSE,'IN_USE'),
('GHANA','Ghana Cedi','GHS','936','2',FALSE,'IN_USE'),
('GIBRALTAR','Gibraltar Pound','GIP','292','2',FALSE,'IN_USE'),
('GREECE','Euro','EUR','978','2',FALSE,'IN_USE'),
('GREENLAND','Danish Krone','DKK','208','2',FALSE,'IN_USE'),
('GRENADA','East Caribbean Dollar','XCD','951','2',FALSE,'IN_USE'),
('GUADELOUPE','Euro','EUR','978','2',FALSE,'IN_USE'),
('GUAM','US Dollar','USD','840','2',FALSE,'IN_USE'),
('GUATEMALA','Quetzal','GTQ','320','2',FALSE,'IN_USE'),
('GUERNSEY','Pound Sterling','GBP','826','2',FALSE,'IN_USE'),
('GUINEA','Guinean Franc','GNF','324','0',FALSE,'IN_USE'),
('GUINEA-BISSAU','CFA Franc BCEAO','XOF','952','0',FALSE,'IN_USE'),
('GUYANA','Guyana Dollar','GYD','328','2',FALSE,'IN_USE'),
('HAITI','Gourde','HTG','332','2',FALSE,'IN_USE'),
('HAITI','US Dollar','USD','840','2',FALSE,'IN_USE'),
('HEARD ISLAND AND McDONALD ISLANDS','Australian Dollar','AUD','036','2',FALSE,'IN_USE'),
('HOLY SEE (THE)','Euro','EUR','978','2',FALSE,'IN_USE'),
('HONDURAS','Lempira','HNL','340','2',FALSE,'IN_USE'),
('HONG KONG','Hong Kong Dollar','HKD','344','2',FALSE,'IN_USE'),
('HUNGARY','Forint','HUF','348','2',FALSE,'IN_USE'),
('ICELAND','Iceland Krona','ISK','352','0',FALSE,'IN_USE'),
('INDIA','Indian Rupee','INR','356','2',FALSE,'IN_USE'),
('INDONESIA','Rupiah','IDR','360','2',FALSE,'IN_USE'),
('INTERNATIONAL MONETARY FUND (IMF) ','SDR (Special Drawing Right)','XDR','960','N.A.',FALSE,'IN_USE'),
('IRAN (ISLAMIC REPUBLIC OF)','Iranian Rial','IRR','364','2',FALSE,'IN_USE'),
('IRAQ','Iraqi Dinar','IQD','368','3',FALSE,'IN_USE'),
('IRELAND','Euro','EUR','978','2',FALSE,'IN_USE'),
('ISLE OF MAN','Pound Sterling','GBP','826','2',FALSE,'IN_USE'),
('ISRAEL','New Israeli Sheqel','ILS','376','2',FALSE,'IN_USE'),
('ITALY','Euro','EUR','978','2',FALSE,'IN_USE'),
('JAMAICA','Jamaican Dollar','JMD','388','2',FALSE,'IN_USE'),
('JAPAN','Yen','JPY','392','0',FALSE,'IN_USE'),
('JERSEY','Pound Sterling','GBP','826','2',FALSE,'IN_USE'),
('JORDAN','Jordanian Dinar','JOD','400','3',FALSE,'IN_USE'),
('KAZAKHSTAN','Tenge','KZT','398','2',FALSE,'IN_USE'),
('KENYA','Kenyan Shilling','KES','404','2',FALSE,'IN_USE'),
('KIRIBATI','Australian Dollar','AUD','036','2',FALSE,'IN_USE'),
('KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)','North Korean Won','KPW','408','2',FALSE,'IN_USE'),
('KOREA (THE REPUBLIC OF)','Won','KRW','410','0',FALSE,'IN_USE'),
('KUWAIT','Kuwaiti Dinar','KWD','414','3',FALSE,'IN_USE'),
('KYRGYZSTAN','Som','KGS','417','2',FALSE,'IN_USE'),
('LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)','Lao Kip','LAK','418','2',FALSE,'IN_USE'),
('LATVIA','Euro','EUR','978','2',FALSE,'IN_USE'),
('LEBANON','Lebanese Pound','LBP','422','2',FALSE,'IN_USE'),
('LESOTHO','Loti','LSL','426','2',FALSE,'IN_USE'),
('LESOTHO','Rand','ZAR','710','2',FALSE,'IN_USE'),
('LIBERIA','Liberian Dollar','LRD','430','2',FALSE,'IN_USE'),
('LIBYA','Libyan Dinar','LYD','434','3',FALSE,'IN_USE'),
('LIECHTENSTEIN','Swiss Franc','CHF','756','2',FALSE,'IN_USE'),
('LITHUANIA','Euro','EUR','978','2',FALSE,'IN_USE'),
('LUXEMBOURG','Euro','EUR','978','2',FALSE,'IN_USE'),
('MACAO','Pataca','MOP','446','2',FALSE,'IN_USE'),
('NORTH MACEDONIA','Denar','MKD','807','2',FALSE,'IN_USE'),
('MADAGASCAR','Malagasy Ariary','MGA','969','2',FALSE,'IN_USE'),
('MALAWI','Malawi Kwacha','MWK','454','2',FALSE,'IN_USE'),
('MALAYSIA','Malaysian Ringgit','MYR','458','2',FALSE,'IN_USE'),
('MALDIVES','Rufiyaa','MVR','462','2',FALSE,'IN_USE'),
('MALI','CFA Franc BCEAO','XOF','952','0',FALSE,'IN_USE'),
('MALTA','Euro','EUR','978','2',FALSE,'IN_USE'),
('MARSHALL ISLANDS (THE)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('MARTINIQUE','Euro','EUR','978','2',FALSE,'IN_USE'),
('MAURITANIA','Ouguiya','MRU','929','2',FALSE,'IN_USE'),
('MAURITIUS','Mauritius Rupee','MUR','480','2',FALSE,'IN_USE'),
('MAYOTTE','Euro','EUR','978','2',FALSE,'IN_USE'),
('MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP','ADB Unit of Account','XUA','965','N.A.',FALSE,'IN_USE'),
('MEXICO','Mexican Peso','MXN','484','2',FALSE,'IN_USE'),
('MEXICO','Mexican Unidad de Inversion (UDI)','MXV','979','2',FALSE,'IN_USE'),
('MICRONESIA (FEDERATED STATES OF)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('MOLDOVA (THE REPUBLIC OF)','Moldovan Leu','MDL','498','2',FALSE,'IN_USE'),
('MONACO','Euro','EUR','978','2',FALSE,'IN_USE'),
('MONGOLIA','Tugrik','MNT','496','2',FALSE,'IN_USE'),
('MONTENEGRO','Euro','EUR','978','2',FALSE,'IN_USE'),
('MONTSERRAT','East Caribbean Dollar','XCD','951','2',FALSE,'IN_USE'),
('MOROCCO','Moroccan Dirham','MAD','504','2',FALSE,'IN_USE'),
('MOZAMBIQUE','Mozambique Metical','MZN','943','2',FALSE,'IN_USE'),
('MYANMAR','Kyat','MMK','104','2',FALSE,'IN_USE'),
('NAMIBIA','Namibia Dollar','NAD','516','2',FALSE,'IN_USE'),
('NAMIBIA','Rand','ZAR','710','2',FALSE,'IN_USE'),
('NAURU','Australian Dollar','AUD','036','2',FALSE,'IN_USE'),
('NEPAL','Nepalese Rupee','NPR','524','2',FALSE,'IN_USE'),
('NETHERLANDS (THE)','Euro','EUR','978','2',FALSE,'IN_USE'),
('NEW CALEDONIA','CFP Franc','XPF','953','0',FALSE,'IN_USE'),
('NEW ZEALAND','New Zealand Dollar','NZD','554','2',FALSE,'IN_USE'),
('NICARAGUA','Cordoba Oro','NIO','558','2',FALSE,'IN_USE'),
('NIGER (THE)','CFA Franc BCEAO','XOF','952','0',FALSE,'IN_USE'),
('NIGERIA','Naira','NGN','566','2',FALSE,'IN_USE'),
('NIUE','New Zealand Dollar','NZD','554','2',FALSE,'IN_USE'),
('NORFOLK ISLAND','Australian Dollar','AUD','036','2',FALSE,'IN_USE'),
('NORTHERN MARIANA ISLANDS (THE)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('NORWAY','Norwegian Krone','NOK','578','2',FALSE,'IN_USE'),
('OMAN','Rial Omani','OMR','512','3',FALSE,'IN_USE'),
('PAKISTAN','Pakistan Rupee','PKR','586','2',FALSE,'IN_USE'),
('PALAU','US Dollar','USD','840','2',FALSE,'IN_USE'),
('PALESTINE, STATE OF','No universal currency',DEFAULT,DEFAULT,DEFAULT,FALSE,'IN_USE'),
('PANAMA','Balboa','PAB','590','2',FALSE,'IN_USE'),
('PANAMA','US Dollar','USD','840','2',FALSE,'IN_USE'),
('PAPUA NEW GUINEA','Kina','PGK','598','2',FALSE,'IN_USE'),
('PARAGUAY','Guarani','PYG','600','0',FALSE,'IN_USE'),
('PERU','Sol','PEN','604','2',FALSE,'IN_USE'),
('PHILIPPINES (THE)','Philippine Peso','PHP','608','2',FALSE,'IN_USE'),
('PITCAIRN','New Zealand Dollar','NZD','554','2',FALSE,'IN_USE'),
('POLAND','Zloty','PLN','985','2',FALSE,'IN_USE'),
('PORTUGAL','Euro','EUR','978','2',FALSE,'IN_USE'),
('PUERTO RICO','US Dollar','USD','840','2',FALSE,'IN_USE'),
('QATAR','Qatari Rial','QAR','634','2',FALSE,'IN_USE'),
('RÉUNION','Euro','EUR','978','2',FALSE,'IN_USE'),
('ROMANIA','Romanian Leu','RON','946','2',FALSE,'IN_USE'),
('RUSSIAN FEDERATION (THE)','Russian Ruble','RUB','643','2',FALSE,'IN_USE'),
('RWANDA','Rwanda Franc','RWF','646','0',FALSE,'IN_USE'),
('SAINT BARTHÉLEMY','Euro','EUR','978','2',FALSE,'IN_USE'),
('SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','Saint Helena Pound','SHP','654','2',FALSE,'IN_USE'),
('SAINT KITTS AND NEVIS','East Caribbean Dollar','XCD','951','2',FALSE,'IN_USE'),
('SAINT LUCIA','East Caribbean Dollar','XCD','951','2',FALSE,'IN_USE'),
('SAINT MARTIN (FRENCH PART)','Euro','EUR','978','2',FALSE,'IN_USE'),
('SAINT PIERRE AND MIQUELON','Euro','EUR','978','2',FALSE,'IN_USE'),
('SAINT VINCENT AND THE GRENADINES','East Caribbean Dollar','XCD','951','2',FALSE,'IN_USE'),
('SAMOA','Tala','WST','882','2',FALSE,'IN_USE'),
('SAN MARINO','Euro','EUR','978','2',FALSE,'IN_USE'),
('SAO TOME AND PRINCIPE','Dobra','STN','930','2',FALSE,'IN_USE'),
('SAUDI ARABIA','Saudi Riyal','SAR','682','2',FALSE,'IN_USE'),
('SENEGAL','CFA Franc BCEAO','XOF','952','0',FALSE,'IN_USE'),
('SERBIA','Serbian Dinar','RSD','941','2',FALSE,'IN_USE'),
('SEYCHELLES','Seychelles Rupee','SCR','690','2',FALSE,'IN_USE'),
('SIERRA LEONE','Leone','SLL','694','2',FALSE,'IN_USE'),
('SIERRA LEONE','Leone','SLE','925','2',FALSE,'IN_USE'),
('SINGAPORE','Singapore Dollar','SGD','702','2',FALSE,'IN_USE'),
('SINT MAARTEN (DUTCH PART)','Netherlands Antillean Guilder','ANG','532','2',FALSE,'IN_USE'),
('SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"','Sucre','XSU','994','N.A.',FALSE,'IN_USE'),
('SLOVAKIA','Euro','EUR','978','2',FALSE,'IN_USE'),
('SLOVENIA','Euro','EUR','978','2',FALSE,'IN_USE'),
('SOLOMON ISLANDS','Solomon Islands Dollar','SBD','090','2',FALSE,'IN_USE'),
('SOMALIA','Somali Shilling','SOS','706','2',FALSE,'IN_USE'),
('SOUTH AFRICA','Rand','ZAR','710','2',FALSE,'IN_USE'),
('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','No universal currency',DEFAULT,DEFAULT,DEFAULT,FALSE,'IN_USE'),
('SOUTH SUDAN','South Sudanese Pound','SSP','728','2',FALSE,'IN_USE'),
('SPAIN','Euro','EUR','978','2',FALSE,'IN_USE'),
('SRI LANKA','Sri Lanka Rupee','LKR','144','2',FALSE,'IN_USE'),
('SUDAN (THE)','Sudanese Pound','SDG','938','2',FALSE,'IN_USE'),
('SURINAME','Surinam Dollar','SRD','968','2',FALSE,'IN_USE'),
('SVALBARD AND JAN MAYEN','Norwegian Krone','NOK','578','2',FALSE,'IN_USE'),
('SWEDEN','Swedish Krona','SEK','752','2',FALSE,'IN_USE'),
('SWITZERLAND','Swiss Franc','CHF','756','2',FALSE,'IN_USE'),
('SWITZERLAND','WIR Euro','CHE','947','2',FALSE,'IN_USE'),
('SWITZERLAND','WIR Franc','CHW','948','2',FALSE,'IN_USE'),
('SYRIAN ARAB REPUBLIC','Syrian Pound','SYP','760','2',FALSE,'IN_USE'),
('TAIWAN (PROVINCE OF CHINA)','New Taiwan Dollar','TWD','901','2',FALSE,'IN_USE'),
('TAJIKISTAN','Somoni','TJS','972','2',FALSE,'IN_USE'),
('TANZANIA, UNITED REPUBLIC OF','Tanzanian Shilling','TZS','834','2',FALSE,'IN_USE'),
('THAILAND','Baht','THB','764','2',FALSE,'IN_USE'),
('TIMOR-LESTE','US Dollar','USD','840','2',FALSE,'IN_USE'),
('TOGO','CFA Franc BCEAO','XOF','952','0',FALSE,'IN_USE'),
('TOKELAU','New Zealand Dollar','NZD','554','2',FALSE,'IN_USE'),
('TONGA','Pa’anga','TOP','776','2',FALSE,'IN_USE'),
('TRINIDAD AND TOBAGO','Trinidad and Tobago Dollar','TTD','780','2',FALSE,'IN_USE'),
('TUNISIA','Tunisian Dinar','TND','788','3',FALSE,'IN_USE'),
('TURKEY','Turkish Lira','TRY','949','2',FALSE,'IN_USE'),
('TURKMENISTAN','Turkmenistan New Manat','TMT','934','2',FALSE,'IN_USE'),
('TURKS AND CAICOS ISLANDS (THE)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('TUVALU','Australian Dollar','AUD','036','2',FALSE,'IN_USE'),
('UGANDA','Uganda Shilling','UGX','800','0',FALSE,'IN_USE'),
('UKRAINE','Hryvnia','UAH','980','2',FALSE,'IN_USE'),
('UNITED ARAB EMIRATES (THE)','UAE Dirham','AED','784','2',FALSE,'IN_USE'),
('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)','Pound Sterling','GBP','826','2',FALSE,'IN_USE'),
('UNITED STATES MINOR OUTLYING ISLANDS (THE)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('UNITED STATES OF AMERICA (THE)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('UNITED STATES OF AMERICA (THE)','US Dollar (Next day)','USN','997','2',FALSE,'IN_USE'),
('URUGUAY','Peso Uruguayo','UYU','858','2',FALSE,'IN_USE'),
('URUGUAY','Uruguay Peso en Unidades Indexadas (UI)','UYI','940','0',FALSE,'IN_USE'),
('URUGUAY','Unidad Previsional','UYW','927','4',FALSE,'IN_USE'),
('UZBEKISTAN','Uzbekistan Sum','UZS','860','2',FALSE,'IN_USE'),
('VANUATU','Vatu','VUV','548','0',FALSE,'IN_USE'),
('VENEZUELA (BOLIVARIAN REPUBLIC OF)','Bolívar Soberano','VES','928','2',FALSE,'IN_USE'),
('VENEZUELA (BOLIVARIAN REPUBLIC OF)','Bolívar Soberano','VED','926','2',FALSE,'IN_USE'),
('VIET NAM','Dong','VND','704','0',FALSE,'IN_USE'),
('VIRGIN ISLANDS (BRITISH)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('VIRGIN ISLANDS (U.S.)','US Dollar','USD','840','2',FALSE,'IN_USE'),
('WALLIS AND FUTUNA','CFP Franc','XPF','953','0',FALSE,'IN_USE'),
('WESTERN SAHARA','Moroccan Dirham','MAD','504','2',FALSE,'IN_USE'),
('YEMEN','Yemeni Rial','YER','886','2',FALSE,'IN_USE'),
('ZAMBIA','Zambian Kwacha','ZMW','967','2',FALSE,'IN_USE'),
('ZIMBABWE','Zimbabwe Dollar','ZWL','932','2',FALSE,'IN_USE'),
('ZZ01_Bond Markets Unit European_EURCO','Bond Markets Unit European Composite Unit (EURCO)','XBA','955','N.A.',FALSE,'IN_USE'),
('ZZ02_Bond Markets Unit European_EMU-6','Bond Markets Unit European Monetary Unit (E.M.U.-6)','XBB','956','N.A.',FALSE,'IN_USE'),
('ZZ03_Bond Markets Unit European_EUA-9','Bond Markets Unit European Unit of Account 9 (E.U.A.-9)','XBC','957','N.A.',FALSE,'IN_USE'),
('ZZ04_Bond Markets Unit European_EUA-17','Bond Markets Unit European Unit of Account 17 (E.U.A.-17)','XBD','958','N.A.',FALSE,'IN_USE'),
('ZZ06_Testing_Code','Codes specifically reserved for testing purposes','XTS','963','N.A.',FALSE,'IN_USE'),
('ZZ07_No_Currency','The codes assigned for transactions where no currency is involved','XXX','999','N.A.',FALSE,'IN_USE'),
('ZZ08_Gold','Gold','XAU','959','N.A.',FALSE,'IN_USE'),
('ZZ09_Palladium','Palladium','XPD','964','N.A.',FALSE,'IN_USE'),
('ZZ10_Platinum','Platinum','XPT','962','N.A.',FALSE,'IN_USE'),
('ZZ11_Silver','Silver','XAG','961','N.A.',FALSE,'IN_USE')